config/routes.rb
Rails.application.routes.draw do

  resources :cats, only: [:index, :show, :new, :create, :edit, :update]
  resources :cat_rental_requests, only: [:index, :show, :new, :create] do
    member {get 'approve'}
    member {get 'deny'}
  end

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = [
    'Blue', 'Grey', 'Black', 'White', 'Orange', 'Red', 'Purple', 'Brown'
  ]
  validates :name, presence: true
  validates :sex, inclusion: { in: %w(M F),
    message: "%{value} is not a valid sex" }
  validates :color, inclusion: { in: COLORS,
    message: "%{value} is not a valid color" }

  has_many :cat_rental_requests,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest, dependent: :destroy

  def age
    (Date.today - self.birth_date).numerator / 365
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :status, inclusion: { in: %w(PENDING DENIED APPROVED),
      message: "%{value} is not a valid status" }
  validates :cat_id, :start_date, :end_date, presence: true
  validate :overlapping_approved_requests

  belongs_to :cat,
    foreign_key: :cat_id,
    class_name: :Cat

  def overlapping_requests?(other_request)
    other_start = other_request.start_date
    other_end = other_request.end_date
    return false if self.id == other_request.id

    other_start.between?(self.start_date, self.end_date) ||
    other_end.between?(self.start_date, self.end_date)
  end

  def overlapping_approved_requests
    CatRentalRequest.where(status: "APPROVED", cat_id: self.cat_id).each do |request|
      if self.overlapping_requests?(request)
        self.errors.add(:start_date, "or end date overlaps with existing request")
        return
      end
    end
  end

  def deny_conflicting_requests
    CatRentalRequest.where(status: "PENDING", cat_id: self.cat_id).each do |request|
      if self.overlapping_requests?(request)
        request.deny!
      end
    end
  end

  def approve!
    CatRentalRequest.transaction do
      self.status = 'APPROVED'
      self.save
      deny_conflicting_requests
    end

  end

  def deny!
    self.status = 'DENIED'
    self.save(validate: false)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def show
    @request = CatRentalRequest.find_by(id: params[:id])
    render :show
  end

  def new
    @request = CatRentalRequest.new
    render :new
  end

  def create
    @request = CatRentalRequest.new(request_params)

    if @request.save
      redirect_to cat_rental_request_url(@request)
    else
      render :new
    end
  end

  def approve
    @request = CatRentalRequest.find_by(id: params[:id])
    @request.approve!
    redirect_to cat_url(@request.cat_id)
  end

  def deny
    @request = CatRentalRequest.find_by(id: params[:id])
    @request.deny!
    redirect_to cat_url(@request.cat_id)
  end

  private

  def request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end

  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end

  end


  private

  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :birth_date, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/_form.html.erb
<% if request.persisted? %>
  <% action_url = cat_rental_request_url(request)%>
<% else %>
  <% action_url = cat_rental_requests_url %>
<% end %>

<form action="<%= action_url %>" method="post">
    <% if request.persisted? %>
      <input type="hidden" name="_method" value="PATCH">
    <% end %>


  <select id="cat_choice" name="cat_rental_request[cat_id]">
    <option disabled selected>-- Select cat --</option>
    <% Cat.all.each do |cat| %>
      <option value="<%=cat.id%>" <%= request.cat_id == cat.id ? "selected" : ""%>> <%=cat.name%> </option>
    <%end%>
  </select>
  <br><br>

  <label for="start_date">Start Date</label>
  <input id="start_date" type="date" name="cat_rental_request[start_date]" value="<%= request.start_date %>">
  <br><br>
  <label for="end_date">End Date</label>
  <input id="end_date" type="date" name="cat_rental_request[end_date]" value="<%= request.end_date %>">
  <br><br>

  <input type="submit" value=" <%= request.persisted? ? "Edit request" : "Create request" %>">

</form>

app/views/cat_rental_requests/new.html.erb
<h1>Make a new rental request!!</h1>

<%= render 'form', request: @request %>

app/views/cat_rental_requests/show.html.erb
<h1>Cat Rental Request</h1>

<table>
  <tr>
    <td>Cat Name</td>
    <td><%= @request.cat.name %></td>
  </tr>
  <tr>
    <td>Cat Age</td>
    <td><%= @request.cat.age %></td>
  </tr>
  <tr>
    <td>Cat Sex</td>
    <td><%= @request.cat.sex %></td>
  </tr>
  <tr>
    <td>Cat Color</td>
    <td><%= @request.cat.color %></td>
  </tr>
  <tr>
    <td>Start Date</td>
    <td><%= @request.start_date %></td>
  </tr>
  <tr>
    <td>End Date</td>
    <td><%= @request.end_date %></td>
  </tr>
  <tr>
    <td>Status</td>
    <td><%= @request.status %></td>
  </tr>
</table>
<br><br>
  <%= link_to "Return to cat list", cats_url %>

app/views/cats/_cat.html.erb
<li>
  <%= link_to "#{cat.name}", cat_url(cat.id) %>
</li>

app/views/cats/_form.html.erb
<% if cat.persisted? %>
  <% action_url = cat_url(cat)%>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action="<%= action_url %>" method="post">
    <% if cat.persisted? %>
      <input type="hidden" name="_method" value="PATCH">
    <% end %>

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">

  <br>
  <br>
  <label for="sex">Sex</label>
  <input id="sex" type="radio" name="cat[sex]" value="M" <%= cat.sex == 'M' ? "checked" : ""%> > M
  <input id="sex" type="radio" name="cat[sex]" value="F" <%= cat.sex == 'F' ? "checked" : ""%> > F
  <br> <br>

  <select id="color" name="cat[color]">
    <option disabled selected>-- Select color --</option>
    <% ['Blue', 'Grey', 'Black', 'White', 'Orange', 'Red', 'Purple', 'Brown'].each do |color| %>
      <option value="<%=color%>" <%= cat.color == color ? "selected" : ""%>> <%=color%> </option>
    <%end%>
  </select>
  <br><br>

  <label for="birth_date">Birthdate</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
  <br><br>

  <label for="description">Description</label>
  <textarea id="description" name="cat[description]">
    <%= cat.description %>
  </textarea>
  <br><br>


  <input type="submit" value=" <%= cat.persisted? ? "Edit cat" : "Create Cat" %>">

</form>

app/views/cats/edit.html.erb
<h1>Edit your cat!</h1>

<%= render 'form', cat: @cat %>

app/views/cats/index.html.erb
<h1>Check out these cats!</h1>

<ul>
  <%= render @cats %>
</ul>

<%= link_to "Request a Rental", new_cat_rental_request_url %>

app/views/cats/new.html.erb
<h1>Make a new Cat!!</h1>

<%= render 'form', cat: @cat %>

app/views/cats/show.html.erb
<h1>Rent <%= @cat.name %>!</h1>

<table>
  <tr>
    <td>Sex</td>
    <td><%= @cat.sex %></td>
  </tr>
  <tr>
    <td>Age</td>
    <td><%= @cat.age %></td>
  </tr>
  <tr>
    <td>Color</td>
    <td><%= @cat.color %></td>
  </tr>
  <tr>
    <td>Description</td>
    <td><%= @cat.description %></td>
  </tr>
</table>
<br><br>
  <h2>Requests for this cat</h2>
  <ul>
    <% @cat.cat_rental_requests.order(:start_date).each do |request| %>
      <li> Start: <%= request.start_date %> End: <%= request.end_date %> <%= request.status %>
        <% if request.status == 'PENDING' %>
          <%= button_to "approve", approve_cat_rental_request_url(request.id), method: :get %>
          <%= button_to "deny", deny_cat_rental_request_url(request.id), method: :get %>
        <% end %>
          </li>
    <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>